item {
    id: 1
    name: 'daisy'
}

item {
    id: 2
    name: 'dandelion'
}
item {
    id: 3
    name: 'magnolia'
}

item {
    id: 4
    name: 'rose'
}
item {
    id: 5
    name: 'tulip'
}

item {
    id: 6
    name: 'water_lily'
}